apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubeecr
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kubeecr
          restartPolicy: Never
          containers:
          - name: kubeecr
            image: ghcr.io/servercentral/kubeecr:latest
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: kubeecr-aws-secrets
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: kubeecr-aws-secrets
                    key: AWS_SECRET_ACCESS_KEY
              - name: AWS_REGION
                value: us-east-1
              - name: AWS_ACCOUNT
                value: '123456789'
              - name: KUBEECR_SELECTOR
                value: 'kubeecr=aws-prod'
              - name: KUBEECR_NAMESPACE
                value: default
